### ISSUE TITLE
model and prediction method not working properly

### ISSUE THREAD

**Issue by d-j-e** [evolbioinfo/pastml#1]
Hi,

I have a large set of SNPs to map against a tree - when I set the model (JC) and prediction method (MAP) just the once (!) this is applied to the first SNP, then all the rest use the the default model and prediction method instead of the ones I want...

Also, is there any specific character to use for missing SNP calls - I used "-" but this was seen as an alternative "state" rather than a missing value.

cheers,
David

**Comment by annazhukova** [comment]
Dear David,

Sorry about this issue. Normally the model/method problem should be fixed since version 1.9.1 (python library and docker), and I have just updated the [website](https://pastml.pasteur.fr/) as well. Could you please check which version of pastml you are experiencing this problem with? 

For the missing values please just leave the corresponding field blank. 

Thanks,
Anna
